Install Yarn (#4)

diff --git a/.github/workflows/test-ecosystem.yml b/.github/workflows/test-ecosystem.yml
--- a/.github/workflows/test-ecosystem.yml
+++ b/.github/workflows/test-ecosystem.yml
@@ -124,6 +124,11 @@ jobs:
           npm install --global pnpm
           echo "pnpm: $(pnpm --version)"
 
+      - name: Install yarn
+        run: |
+          npm install --global yarn
+          echo "yarn: $(yarn --version)"
+
       - name: Install dependencies
         continue-on-error: true
         run: npm install --no-audit
@@ -138,4 +143,4 @@ jobs:
           PACKAGE: ${{ matrix.package }}
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
         run: |
-          npm test || echo "::error title=${PACKAGE}::The test failed. Visit ${PACKAGE_URL}."
+          npm test || echo "::error title=${PACKAGE}::The test failed. Visit ${PACKAGE_URL}"
