Make error messages clearer instead of `continue-on-error`

diff --git a/.github/workflows/test-ecosystem.yml b/.github/workflows/test-ecosystem.yml
--- a/.github/workflows/test-ecosystem.yml
+++ b/.github/workflows/test-ecosystem.yml
@@ -141,30 +141,46 @@ jobs:
           echo "yarn: $(yarn --version)"
 
       - name: Install dependencies
-        continue-on-error: true
         working-directory: ${{ steps.repo-info.outputs.directory }}
         env:
           PACKAGE: ${{ matrix.package }}
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
         run: |
-          npm install --no-audit || echo "::error title=${PACKAGE}::The dependency installation failed. Visit ${PACKAGE_URL}"
+          if ! npm install --no-audit; then
+            echo "::error title=${PACKAGE}::The dependency installation failed. Visit ${PACKAGE_URL}"
+            exit 1
+          fi
 
       - name: Install Stylelint ${{ matrix.stylelint-version }}
-        continue-on-error: true
         working-directory: ${{ steps.repo-info.outputs.directory }}
         env:
           STYLELINT_VERSION: ${{ matrix.stylelint-version }}
           PACKAGE: ${{ matrix.package }}
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
         run: |
-          npm install --no-audit --no-save "${STYLELINT_VERSION}" || echo "::error title=${PACKAGE}::The Stylelint installation failed. Visit ${PACKAGE_URL}"
+          if ! npm install --no-audit --no-save "${STYLELINT_VERSION}"; then
+            echo "::error title=${PACKAGE}::The Stylelint (${STYLELINT_VERSION}) installation failed. Visit ${PACKAGE_URL}"
+            exit 1
+          fi
 
-      - name: Run test
-        continue-on-error: true
+      - name: Run build
         working-directory: ${{ steps.repo-info.outputs.directory }}
         env:
           PACKAGE: ${{ matrix.package }}
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
         run: |
-          npm run build --if-present
-          npm test || echo "::error title=${PACKAGE}::The test failed. Visit ${PACKAGE_URL}"
+          if ! npm run build --if-present; then
+            echo "::error title=${PACKAGE}::The build failed. Visit ${PACKAGE_URL}"
+            exit 1
+          fi
+
+      - name: Run test
+        working-directory: ${{ steps.repo-info.outputs.directory }}
+        env:
+          PACKAGE: ${{ matrix.package }}
+          PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
+        run: |
+          if ! npm test; then
+            echo "::error title=${PACKAGE}::The test failed. Visit ${PACKAGE_URL}"
+            exit 1
+          fi
